version: '3'
services:
  activemq:
    image: webcenter/activemq:latest
    container_name: youthchina-activemq
    networks:
      backend:
        ipv4_address: 172.29.1.1
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    volumes:
      - /data/activemq:/data
      - /var/log/activemq:/var/log/activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: root
      ACTIVEMQ_ADMIN_PASSWORD: rootpass
networks:
  backend:
    ipam:
      config:
        - subnet: 172.29.0.0/16