version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmqpass
  courier:
    image: youthchina:courier
    container_name: youthchina-courier
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      backend:
        ipv4_address: 172.29.1.2
    volumes:
      - backenddata:/app/static
networks:
  backend:
    ipam:
      config:
        - subnet: 172.29.0.0/16
volumes:
  rabbitmqdata:
  backenddata: